export default function WorldMap() {
  return (
    <div>
      <h1>World Map</h1>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
      <p>haha</p>
    </div>
  );
}
